function Hd = filterer
%FILTERER Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 8.0 and the DSP System Toolbox 8.3.
%
% Generated on: 03-May-2013 11:07:45
%

Fpass = 10;  % Passband Frequency
Fstop = 12;  % Stopband Frequency
Apass = 1;   % Passband Ripple (dB)
Astop = 60;  % Stopband Attenuation (dB)
Fs    = 30;  % Sampling Frequency

h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);

Hd = design(h, 'ifir');



% [EOF]
