function y = filterer2(x)
%FILTERER2 Filters input x and returns output y.

%
% MATLAB Code
% Generated by MATLAB(R) 8.0 and the DSP System Toolbox 8.3.
%
% Generated on: 03-May-2013 11:07:59
%

persistent Hd;

if isempty(Hd)
    
    Fpass = 10;  % Passband Frequency
    Fstop = 12;  % Stopband Frequency
    Apass = 1;   % Passband Ripple (dB)
    Astop = 60;  % Stopband Attenuation (dB)
    Fs    = 30;  % Sampling Frequency
    
    h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);
    
    Hd = design(h, 'ifir');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);


% [EOF]
